---

- hosts: lamp
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - firewall
    - ntp
    - mysql
    - apache
    - php
    - php-mysql

---

- hosts: solr
  gather_facts: yes

  vars:
    java_packages:
      - openjdk-8-jdk
    firewall_allowed_tcp_ports:
      - "22"
      - "8983"

  pre_tasks:
    - name: Install repo for Java 8.
      apt_repository: repo=ppa:openjdk-r/ppa

  roles:
    - firewall
    - java
    - solr

---

- hosts: nodejs
  gather_facts: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600
      become: yes

  roles:
    - firewall
    - nodejs

  tasks:
    - name: Ensure Node.js API app is present.
      git:
        repo: "{{ app_repository }}"
        version: "{{ app_version }}"
        dest: "{{ app_directory }}"
        accept_hostkey: true
      register: app_updated
      notify: restart forever apps

    - name: Stop all running instances of the app.
      command: "forever stopall"
      when: app_updated.changed

    - name: Ensure Node.js API app dependencies are present.
      npm: "path={{ app_directory }}"
      when: app_updated.changed

    - name: Run Node.js API app tests.
      command: "npm test chdir={{ app_directory }}"
      when: app_updated.changed

    - name: Get list of all running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: Ensure Node.js API app is started.
      command: "forever start {{ app_directory }}/app.js"
      when: "forever_list.stdout.find('app.js') == -1"

    - name: Add cron entry to start Node.js API app on reboot.
      cron:
        name: "Start Node.js API app"
        special_time: reboot
        job: "forever start {{ app_directory }}/app.js"

  handlers:
    - name: restart forever apps
      command: "forever restartall"
